"""add_transactions_table_and_portfolio_relationship

Revision ID: 4212fba071aa
Revises: 6538f3943e9e
Create Date: 2025-07-13 19:57:53.801380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4212fba071aa'
down_revision = '6538f3943e9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DISTRIBUTION', 'TRANSFER_IN', 'TRANSFER_OUT', 'SPLIT', 'MERGER', 'SPINOFF', name='transactiontype'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('security_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('tax_lot_id', sa.String(length=100), nullable=True),
    sa.Column('wash_sale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('from_portfolio_id', sa.Integer(), nullable=True),
    sa.Column('to_portfolio_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['to_portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transactions_symbol'), 'transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_portfolio_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('symbol', sa.VARCHAR(length=20), nullable=False),
    sa.Column('data_date', sa.DATE(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=15, scale=4), nullable=False),
    sa.Column('change_amount', sa.NUMERIC(precision=15, scale=4), nullable=True),
    sa.Column('change_percent', sa.NUMERIC(precision=8, scale=4), nullable=True),
    sa.Column('volume', sa.BIGINT(), nullable=True),
    sa.Column('market_cap', sa.BIGINT(), nullable=True),
    sa.Column('pe_ratio', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.NUMERIC(precision=5, scale=4), nullable=True),
    sa.Column('beta', sa.NUMERIC(precision=6, scale=4), nullable=True),
    sa.Column('fifty_two_week_high', sa.NUMERIC(precision=15, scale=4), nullable=True),
    sa.Column('fifty_two_week_low', sa.NUMERIC(precision=15, scale=4), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'data_date')
    )
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_table('reports',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=17), nullable=False),
    sa.Column('report_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_format', sa.VARCHAR(length=4), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_scheduled', sa.BOOLEAN(), nullable=True),
    sa.Column('schedule_frequency', sa.VARCHAR(length=9), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_reports_portfolio_id'), 'reports', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_symbol'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###