"""add_goals_table

Revision ID: 6538f3943e9e
Revises: 9ce560799de2
Create Date: 2025-07-13 17:33:05.313725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6538f3943e9e'
down_revision = '9ce560799de2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###